export const regions = [
    {label: "US", value: "US"},
    {label: "EU", value: "EU"},
    {label: "TW", value: "TW"},
    {label: "KR", value: "KR"}
];

export const euServers = [
    {label: "Aegwynn", value: "aegwynn-us"},
    {label: "Aerie Peak", value: "aerie peak-us"},
    {label: "Agamaggan", value: "agamaggan-us"},
    {label: "Aggra (Português)", value: "aggra-us"},
    {label: "Aggramar", value: "aggramar-us"},
    {label: "Ahn'Qiraj", value: "ahn'qiraj-us"},
    {label: "Al'Akir", value: "al'akir-us"},
    {label: "Alexstrasza", value: "alexstrasza-us"},
    {label: "Alleria", value: "alleria-us"},
    {label: "Alonsus", value: "alonsus-us"},
    {label: "Aman'Thul", value: "aman'thul-us"},
    {label: "Ambossar", value: "ambossar-us"},
    {label: "Anachronos", value: "anachronos-us"},
    {label: "Anetheron", value: "anetheron-us"},
    {label: "Antonidas", value: "antonidas-us"},
    {label: "Anub'arak", value: "anub'arak-us"},
    {label: "Arak-arahm", value: "arak-arahm-us"},
    {label: "Arathi", value: "arathi-us"},
    {label: "Arathor", value: "arathor-us"},
    {label: "Archimonde", value: "archimonde-us"},
    {label: "Area 52", value: "area 52-us"},
    {label: "Argent Dawn", value: "argent dawn-us"},
    {label: "Arthas", value: "arthas-us"},
    {label: "Arygos", value: "arygos-us"},
    {label: "Ashenvale", value: "ashenvale-us"},
    {label: "Aszune", value: "aszune-us"},
    {label: "Auchindoun", value: "auchindoun-us"},
    {label: "Azjol-Nerub", value: "azjol-nerub-us"},
    {label: "Azshara", value: "azshara-us"},
    {label: "Azuregos", value: "azuregos-us"},
    {label: "Azuremyst", value: "azuremyst-us"},
    {label: "Baelgun", value: "baelgun-us"},
    {label: "Balnazzar", value: "balnazzar-us"},
    {label: "Blackhand", value: "blackhand-us"},
    {label: "Blackmoore", value: "blackmoore-us"},
    {label: "Blackrock", value: "blackrock-us"},
    {label: "Blackscar", value: "blackscar-us"},
    {label: "Blade's Edge", value: "blade's edge-us"},
    {label: "Bladefist", value: "bladefist-us"},
    {label: "Bloodfeather", value: "bloodfeather-us"},
    {label: "Bloodhoof", value: "bloodhoof-us"},
    {label: "Bloodscalp", value: "bloodscalp-us"},
    {label: "Blutkessel", value: "blutkessel-us"},
    {label: "Booty Bay", value: "booty bay-us"},
    {label: "Borean Tundra", value: "borean tundra-us"},
    {label: "Boulderfist", value: "boulderfist-us"},
    {label: "Bronze Dragonflight", value: "bronze dragonflight-us"},
    {label: "Bronzebeard", value: "bronzebeard-us"},
    {label: "Burning Blade", value: "burning blade-us"},
    {label: "Burning Legion", value: "burning legion-us"},
    {label: "Burning Steppes", value: "burning steppes-us"},
    {label: "C'Thun", value: "c'thun-us"},
    {label: "Chamber of Aspects", value: "chamber of aspects-us"},
    {label: "Chants éternels", value: "chants éternels-us"},
    {label: "Cho'gall", value: "cho'gall-us"},
    {label: "Chromaggus", value: "chromaggus-us"},
    {label: "Colinas Pardas", value: "colinas pardas-us"},
    {label: "Confrérie du Thorium", value: "confrérie du thorium-us"},
    {label: "Conseil des Ombres", value: "conseil des ombres-us"},
    {label: "Crushridge", value: "crushridge-us"},
    {label: "Culte de la Rive noire", value: "culte de la rive noire-us"},
    {label: "Daggerspine", value: "daggerspine-us"},
    {label: "Dalaran", value: "dalaran-us"},
    {label: "Dalvengyr", value: "dalvengyr-us"},
    {label: "Darkmoon Faire", value: "darkmoon faire-us"},
    {label: "Darksorrow", value: "darksorrow-us"},
    {label: "Darkspear", value: "darkspear-us"},
    {label: "Das Konsortium", value: "das konsortium-us"},
    {label: "Das Syndikat", value: "das syndikat-us"},
    {label: "Deathguard", value: "deathguard-us"},
    {label: "Deathweaver", value: "deathweaver-us"},
    {label: "Deathwing", value: "deathwing-us"},
    {label: "Deepholm", value: "deepholm-us"},
    {label: "Defias Brotherhood", value: "defias brotherhood-us"},
    {label: "Dentarg", value: "dentarg-us"},
    {label: "Der Mithrilorden", value: "der mithrilorden-us"},
    {label: "Der Rat von Dalaran", value: "der rat von dalaran-us"},
    {label: "Der abyssische Rat", value: "der abyssische rat-us"},
    {label: "Destromath", value: "destromath-us"},
    {label: "Dethecus", value: "dethecus-us"},
    {label: "Die Aldor", value: "die aldor-us"},
    {label: "Die Arguswacht", value: "die arguswacht-us"},
    {label: "Die Nachtwache", value: "die nachtwache-us"},
    {label: "Die Silberne Hand", value: "die silberne hand-us"},
    {label: "Die Todeskrallen", value: "die todeskrallen-us"},
    {label: "Die ewige Wacht", value: "die ewige wacht-us"},
    {label: "Doomhammer", value: "doomhammer-us"},
    {label: "Draenor", value: "draenor-us"},
    {label: "Dragonblight", value: "dragonblight-us"},
    {label: "Dragonmaw", value: "dragonmaw-us"},
    {label: "Drak'thul", value: "drak'thul-us"},
    {label: "Drek'Thar", value: "drek'thar-us"},
    {label: "Dun Modr", value: "dun modr-us"},
    {label: "Dun Morogh", value: "dun morogh-us"},
    {label: "Dunemaul", value: "dunemaul-us"},
    {label: "Durotan", value: "durotan-us"},
    {label: "Earthen Ring", value: "earthen ring-us"},
    {label: "Echsenkessel", value: "echsenkessel-us"},
    {label: "Eitrigg", value: "eitrigg-us"},
    {label: "Eldre'Thalas", value: "eldre'thalas-us"},
    {label: "Elune", value: "elune-us"},
    {label: "Emerald Dream", value: "emerald dream-us"},
    {label: "Emeriss", value: "emeriss-us"},
    {label: "Eonar", value: "eonar-us"},
    {label: "Eredar", value: "eredar-us"},
    {label: "Eversong", value: "eversong-us"},
    {label: "Executus", value: "executus-us"},
    {label: "Exodar", value: "exodar-us"},
    {label: "Festung der Stürme", value: "festung der stürme-us"},
    {label: "Fordragon", value: "fordragon-us"},
    {label: "Forscherliga", value: "forscherliga-us"},
    {label: "Frostmane", value: "frostmane-us"},
    {label: "Frostmourne", value: "frostmourne-us"},
    {label: "Frostwhisper", value: "frostwhisper-us"},
    {label: "Frostwolf", value: "frostwolf-us"},
    {label: "Galakrond", value: "galakrond-us"},
    {label: "Garona", value: "garona-us"},
    {label: "Garrosh", value: "garrosh-us"},
    {label: "Genjuros", value: "genjuros-us"},
    {label: "Ghostlands", value: "ghostlands-us"},
    {label: "Gilneas", value: "gilneas-us"},
    {label: "Goldrinn", value: "goldrinn-us"},
    {label: "Gordunni", value: "gordunni-us"},
    {label: "Gorgonnash", value: "gorgonnash-us"},
    {label: "Greymane", value: "greymane-us"},
    {label: "Grim Batol", value: "grim batol-us"},
    {label: "Grom", value: "grom-us"},
    {label: "Gul'dan", value: "gul'dan-us"},
    {label: "Hakkar", value: "hakkar-us"},
    {label: "Haomarush", value: "haomarush-us"},
    {label: "Hellfire", value: "hellfire-us"},
    {label: "Hellscream", value: "hellscream-us"},
    {label: "Howling Fjord", value: "howling fjord-us"},
    {label: "Hyjal", value: "hyjal-us"},
    {label: "Illidan", value: "illidan-us"},
    {label: "Jaedenar", value: "jaedenar-us"},
    {label: "Kael'thas", value: "kael'thas-us"},
    {label: "Karazhan", value: "karazhan-us"},
    {label: "Kargath", value: "kargath-us"},
    {label: "Kazzak", value: "kazzak-us"},
    {label: "Kel'Thuzad", value: "kel'thuzad-us"},
    {label: "Khadgar", value: "khadgar-us"},
    {label: "Khaz Modan", value: "khaz modan-us"},
    {label: "Khaz'goroth", value: "khaz'goroth-us"},
    {label: "Kil'jaeden", value: "kil'jaeden-us"},
    {label: "Kilrogg", value: "kilrogg-us"},
    {label: "Kirin Tor", value: "kirin tor-us"},
    {label: "Kor'gall", value: "kor'gall-us"},
    {label: "Krag'jin", value: "krag'jin-us"},
    {label: "Krasus", value: "krasus-us"},
    {label: "Kul Tiras", value: "kul tiras-us"},
    {label: "Kult der Verdammten", value: "kult der verdammten-us"},
    {label: "La Croisade écarlate", value: "la croisade écarlate-us"},
    {label: "Laughing Skull", value: "laughing skull-us"},
    {label: "Les Clairvoyants", value: "les clairvoyants-us"},
    {label: "Les Sentinelles", value: "les sentinelles-us"},
    {label: "Lich King", value: "lich king-us"},
    {label: "Lightbringer", value: "lightbringer-us"},
    {label: "Lightning's Blade", value: "lightning's blade-us"},
    {label: "Lordaeron", value: "lordaeron-us"},
    {label: "Los Errantes", value: "los errantes-us"},
    {label: "Lothar", value: "lothar-us"},
    {label: "Madmortem", value: "madmortem-us"},
    {label: "Magtheridon", value: "magtheridon-us"},
    {label: "Mal'Ganis", value: "mal'ganis-us"},
    {label: "Malfurion", value: "malfurion-us"},
    {label: "Malorne", value: "malorne-us"},
    {label: "Malygos", value: "malygos-us"},
    {label: "Mannoroth", value: "mannoroth-us"},
    {label: "Marécage de Zangar", value: "marécage de zangar-us"},
    {label: "Mazrigos", value: "mazrigos-us"},
    {label: "Medivh", value: "medivh-us"},
    {label: "Minahonda", value: "minahonda-us"},
    {label: "Moonglade", value: "moonglade-us"},
    {label: "Mug'thol", value: "mug'thol-us"},
    {label: "Nagrand", value: "nagrand-us"},
    {label: "Nathrezim", value: "nathrezim-us"},
    {label: "Naxxramas", value: "naxxramas-us"},
    {label: "Nazjatar", value: "nazjatar-us"},
    {label: "Nefarian", value: "nefarian-us"},
    {label: "Nemesis", value: "nemesis-us"},
    {label: "Neptulon", value: "neptulon-us"},
    {label: "Ner'zhul", value: "ner'zhul-us"},
    {label: "Nera'thor", value: "nera'thor-us"},
    {label: "Nethersturm", value: "nethersturm-us"},
    {label: "Nordrassil", value: "nordrassil-us"},
    {label: "Norgannon", value: "norgannon-us"},
    {label: "Nozdormu", value: "nozdormu-us"},
    {label: "Onyxia", value: "onyxia-us"},
    {label: "Outland", value: "outland-us"},
    {label: "Perenolde", value: "perenolde-us"},
    {label: "Pozzo dell'Eternità", value: "pozzo dell'eternità-us"},
    {label: "Proudmoore", value: "proudmoore-us"},
    {label: "Quel'Thalas", value: "quel'thalas-us"},
    {label: "Ragnaros", value: "ragnaros-us"},
    {label: "Rajaxx", value: "rajaxx-us"},
    {label: "Rashgarroth", value: "rashgarroth-us"},
    {label: "Ravencrest", value: "ravencrest-us"},
    {label: "Ravenholdt", value: "ravenholdt-us"},
    {label: "Razuvious", value: "razuvious-us"},
    {label: "Rexxar", value: "rexxar-us"},
    {label: "Runetotem", value: "runetotem-us"},
    {label: "Sanguino", value: "sanguino-us"},
    {label: "Sargeras", value: "sargeras-us"},
    {label: "Saurfang", value: "saurfang-us"},
    {label: "Scarshield Legion", value: "scarshield legion-us"},
    {label: "Sen'jin", value: "sen'jin-us"},
    {label: "Shadowsong", value: "shadowsong-us"},
    {label: "Shattered Halls", value: "shattered halls-us"},
    {label: "Shattered Hand", value: "shattered hand-us"},
    {label: "Shattrath", value: "shattrath-us"},
    {label: "Shen'dralar", value: "shen'dralar-us"},
    {label: "Silvermoon", value: "silvermoon-us"},
    {label: "Sinstralis", value: "sinstralis-us"},
    {label: "Skullcrusher", value: "skullcrusher-us"},
    {label: "Soulflayer", value: "soulflayer-us"},
    {label: "Spinebreaker", value: "spinebreaker-us"},
    {label: "Sporeggar", value: "sporeggar-us"},
    {label: "Steamwheedle Cartel", value: "steamwheedle cartel-us"},
    {label: "Stormrage", value: "stormrage-us"},
    {label: "Stormreaver", value: "stormreaver-us"},
    {label: "Stormscale", value: "stormscale-us"},
    {label: "Sunstrider", value: "sunstrider-us"},
    {label: "Suramar", value: "suramar-us"},
    {label: "Sylvanas", value: "sylvanas-us"},
    {label: "Taerar", value: "taerar-us"},
    {label: "Talnivarr", value: "talnivarr-us"},
    {label: "Tarren Mill", value: "tarren mill-us"},
    {label: "Teldrassil", value: "teldrassil-us"},
    {label: "Temple noir", value: "temple noir-us"},
    {label: "Terenas", value: "terenas-us"},
    {label: "Terokkar", value: "terokkar-us"},
    {label: "Terrordar", value: "terrordar-us"},
    {label: "The Maelstrom", value: "the maelstrom-us"},
    {label: "The Sha'tar", value: "the sha'tar-us"},
    {label: "The Venture Co", value: "the venture co-us"},
    {label: "Theradras", value: "theradras-us"},
    {label: "Thermaplugg", value: "thermaplugg-us"},
    {label: "Thrall", value: "thrall-us"},
    {label: "Throk'Feroth", value: "throk'feroth-us"},
    {label: "Thunderhorn", value: "thunderhorn-us"},
    {label: "Tichondrius", value: "tichondrius-us"},
    {label: "Tirion", value: "tirion-us"},
    {label: "Todeswache", value: "todeswache-us"},
    {label: "Trollbane", value: "trollbane-us"},
    {label: "Turalyon", value: "turalyon-us"},
    {label: "Twilight's Hammer", value: "twilight's hammer-us"},
    {label: "Twisting Nether", value: "twisting nether-us"},
    {label: "Tyrande", value: "tyrande-us"},
    {label: "Uldaman", value: "uldaman-us"},
    {label: "Ulduar", value: "ulduar-us"},
    {label: "Uldum", value: "uldum-us"},
    {label: "Un'Goro", value: "un'goro-us"},
    {label: "Varimathras", value: "varimathras-us"},
    {label: "Vashj", value: "vashj-us"},
    {label: "Vek'lor", value: "vek'lor-us"},
    {label: "Vek'nilash", value: "vek'nilash-us"},
    {label: "Vol'jin", value: "vol'jin-us"},
    {label: "Wildhammer", value: "wildhammer-us"},
    {label: "Wrathbringer", value: "wrathbringer-us"},
    {label: "Xavius", value: "xavius-us"},
    {label: "Ysera", value: "ysera-us"},
    {label: "Ysondre", value: "ysondre-us"},
    {label: "Zenedar", value: "zenedar-us"},
    {label: "Zirkel des Cenarius", value: "zirkel des cenarius-us"},
    {label: "Zul'jin", value: "zul'jin-us"},
    {label: "Zuluhed", value: "zuluhed-us"}
]

export const usServers = [
    {label: "Aegwynn", value: "aegwynn-eu"},
    {label: "Aerie Peak", value: "aerie peak-eu"},
    {label: "Agamaggan", value: "agamaggan-eu"},
    {label: "Aggramar", value: "aggramar-eu"},
    {label: "Akama", value: "akama-eu"},
    {label: "Alexstrasza", value: "alexstrasza-eu"},
    {label: "Alleria", value: "alleria-eu"},
    {label: "Altar of Storms", value: "altar of storms-eu"},
    {label: "Alterac Mountains", value: "alterac mountains-eu"},
    {label: "Aman'Thul", value: "aman'thul-eu"},
    {label: "Andorhal", value: "andorhal-eu"},
    {label: "Anetheron", value: "anetheron-eu"},
    {label: "Antonidas", value: "antonidas-eu"},
    {label: "Anub'arak", value: "anub'arak-eu"},
    {label: "Anvilmar", value: "anvilmar-eu"},
    {label: "Arathor", value: "arathor-eu"},
    {label: "Archimonde", value: "archimonde-eu"},
    {label: "Area 52", value: "area 52-eu"},
    {label: "Argent Dawn", value: "argent dawn-eu"},
    {label: "Arthas", value: "arthas-eu"},
    {label: "Arygos", value: "arygos-eu"},
    {label: "Auchindoun", value: "auchindoun-eu"},
    {label: "Azgalor", value: "azgalor-eu"},
    {label: "Azjol-Nerub", value: "azjol-nerub-eu"},
    {label: "Azralon", value: "azralon-eu"},
    {label: "Azshara", value: "azshara-eu"},
    {label: "Azuremyst", value: "azuremyst-eu"},
    {label: "Baelgun", value: "baelgun-eu"},
    {label: "Balnazzar", value: "balnazzar-eu"},
    {label: "Barthilas", value: "barthilas-eu"},
    {label: "Black Dragonflight", value: "black dragonflight-eu"},
    {label: "Blackhand", value: "blackhand-eu"},
    {label: "Blackrock", value: "blackrock-eu"},
    {label: "Blackwater Raiders", value: "blackwater raiders-eu"},
    {label: "Blackwing Lair", value: "blackwing lair-eu"},
    {label: "Blade's Edge", value: "blade's edge-eu"},
    {label: "Bladefist", value: "bladefist-eu"},
    {label: "Bleeding Hollow", value: "bleeding hollow-eu"},
    {label: "Blood Furnace", value: "blood furnace-eu"},
    {label: "Bloodhoof", value: "bloodhoof-eu"},
    {label: "Bloodscalp", value: "bloodscalp-eu"},
    {label: "Bonechewer", value: "bonechewer-eu"},
    {label: "Borean Tundra", value: "borean tundra-eu"},
    {label: "Boulderfist", value: "boulderfist-eu"},
    {label: "Bronzebeard", value: "bronzebeard-eu"},
    {label: "Burning Blade", value: "burning blade-eu"},
    {label: "Burning Legion", value: "burning legion-eu"},
    {label: "Caelestrasz", value: "caelestrasz-eu"},
    {label: "Cairne", value: "cairne-eu"},
    {label: "Cenarion Circle", value: "cenarion circle-eu"},
    {label: "Cenarius", value: "cenarius-eu"},
    {label: "Cho'gall", value: "cho'gall-eu"},
    {label: "Chromaggus", value: "chromaggus-eu"},
    {label: "Coilfang", value: "coilfang-eu"},
    {label: "Crushridge", value: "crushridge-eu"},
    {label: "Daggerspine", value: "daggerspine-eu"},
    {label: "Dalaran", value: "dalaran-eu"},
    {label: "Dalvengyr", value: "dalvengyr-eu"},
    {label: "Dark Iron", value: "dark iron-eu"},
    {label: "Darkspear", value: "darkspear-eu"},
    {label: "Darrowmere", value: "darrowmere-eu"},
    {label: "Dath'Remar", value: "dath'remar-eu"},
    {label: "Dawnbringer", value: "dawnbringer-eu"},
    {label: "Deathwing", value: "deathwing-eu"},
    {label: "Demon Soul", value: "demon soul-eu"},
    {label: "Dentarg", value: "dentarg-eu"},
    {label: "Destromath", value: "destromath-eu"},
    {label: "Dethecus", value: "dethecus-eu"},
    {label: "Detheroc", value: "detheroc-eu"},
    {label: "Doomhammer", value: "doomhammer-eu"},
    {label: "Draenor", value: "draenor-eu"},
    {label: "Dragonblight", value: "dragonblight-eu"},
    {label: "Dragonmaw", value: "dragonmaw-eu"},
    {label: "Drak'Tharon", value: "drak'tharon-eu"},
    {label: "Drak'thul", value: "drak'thul-eu"},
    {label: "Draka", value: "draka-eu"},
    {label: "Drakkari", value: "drakkari-eu"},
    {label: "Dreadmaul", value: "dreadmaul-eu"},
    {label: "Drenden", value: "drenden-eu"},
    {label: "Dunemaul", value: "dunemaul-eu"},
    {label: "Durotan", value: "durotan-eu"},
    {label: "Duskwood", value: "duskwood-eu"},
    {label: "Earthen Ring", value: "earthen ring-eu"},
    {label: "Echo Isles", value: "echo isles-eu"},
    {label: "Eitrigg", value: "eitrigg-eu"},
    {label: "Eldre'Thalas", value: "eldre'thalas-eu"},
    {label: "Elune", value: "elune-eu"},
    {label: "Emerald Dream", value: "emerald dream-eu"},
    {label: "Eonar", value: "eonar-eu"},
    {label: "Eredar", value: "eredar-eu"},
    {label: "Executus", value: "executus-eu"},
    {label: "Exodar", value: "exodar-eu"},
    {label: "Farstriders", value: "farstriders-eu"},
    {label: "Feathermoon", value: "feathermoon-eu"},
    {label: "Fenris", value: "fenris-eu"},
    {label: "Firetree", value: "firetree-eu"},
    {label: "Fizzcrank", value: "fizzcrank-eu"},
    {label: "Frostmane", value: "frostmane-eu"},
    {label: "Frostmourne", value: "frostmourne-eu"},
    {label: "Frostwolf", value: "frostwolf-eu"},
    {label: "Galakrond", value: "galakrond-eu"},
    {label: "Gallywix", value: "gallywix-eu"},
    {label: "Garithos", value: "garithos-eu"},
    {label: "Garona", value: "garona-eu"},
    {label: "Garrosh", value: "garrosh-eu"},
    {label: "Ghostlands", value: "ghostlands-eu"},
    {label: "Gilneas", value: "gilneas-eu"},
    {label: "Gnomeregan", value: "gnomeregan-eu"},
    {label: "Goldrinn", value: "goldrinn-eu"},
    {label: "Gorefiend", value: "gorefiend-eu"},
    {label: "Gorgonnash", value: "gorgonnash-eu"},
    {label: "Greymane", value: "greymane-eu"},
    {label: "Grizzly Hills", value: "grizzly hills-eu"},
    {label: "Gul'dan", value: "gul'dan-eu"},
    {label: "Gundrak", value: "gundrak-eu"},
    {label: "Gurubashi", value: "gurubashi-eu"},
    {label: "Hakkar", value: "hakkar-eu"},
    {label: "Haomarush", value: "haomarush-eu"},
    {label: "Hellscream", value: "hellscream-eu"},
    {label: "Hydraxis", value: "hydraxis-eu"},
    {label: "Hyjal", value: "hyjal-eu"},
    {label: "Icecrown", value: "icecrown-eu"},
    {label: "Illidan", value: "illidan-eu"},
    {label: "Jaedenar", value: "jaedenar-eu"},
    {label: "Jubei'Thos", value: "jubei'thos-eu"},
    {label: "Kael'thas", value: "kael'thas-eu"},
    {label: "Kalecgos", value: "kalecgos-eu"},
    {label: "Kargath", value: "kargath-eu"},
    {label: "Kel'Thuzad", value: "kel'thuzad-eu"},
    {label: "Khadgar", value: "khadgar-eu"},
    {label: "Khaz Modan", value: "khaz modan-eu"},
    {label: "Khaz'goroth", value: "khaz'goroth-eu"},
    {label: "Kil'jaeden", value: "kil'jaeden-eu"},
    {label: "Kilrogg", value: "kilrogg-eu"},
    {label: "Kirin Tor", value: "kirin tor-eu"},
    {label: "Korgath", value: "korgath-eu"},
    {label: "Korialstrasz", value: "korialstrasz-eu"},
    {label: "Kul Tiras", value: "kul tiras-eu"},
    {label: "Laughing Skull", value: "laughing skull-eu"},
    {label: "Lethon", value: "lethon-eu"},
    {label: "Lightbringer", value: "lightbringer-eu"},
    {label: "Lightning's Blade", value: "lightning's blade-eu"},
    {label: "Lightninghoof", value: "lightninghoof-eu"},
    {label: "Llane", value: "llane-eu"},
    {label: "Lothar", value: "lothar-eu"},
    {label: "Madoran", value: "madoran-eu"},
    {label: "Maelstrom", value: "maelstrom-eu"},
    {label: "Magtheridon", value: "magtheridon-eu"},
    {label: "Maiev", value: "maiev-eu"},
    {label: "Mal'Ganis", value: "mal'ganis-eu"},
    {label: "Malfurion", value: "malfurion-eu"},
    {label: "Malorne", value: "malorne-eu"},
    {label: "Malygos", value: "malygos-eu"},
    {label: "Mannoroth", value: "mannoroth-eu"},
    {label: "Medivh", value: "medivh-eu"},
    {label: "Misha", value: "misha-eu"},
    {label: "Mok'Nathal", value: "mok'nathal-eu"},
    {label: "Moon Guard", value: "moon guard-eu"},
    {label: "Moonrunner", value: "moonrunner-eu"},
    {label: "Mug'thol", value: "mug'thol-eu"},
    {label: "Muradin", value: "muradin-eu"},
    {label: "Nagrand", value: "nagrand-eu"},
    {label: "Nathrezim", value: "nathrezim-eu"},
    {label: "Nazgrel", value: "nazgrel-eu"},
    {label: "Nazjatar", value: "nazjatar-eu"},
    {label: "Nemesis", value: "nemesis-eu"},
    {label: "Ner'zhul", value: "ner'zhul-eu"},
    {label: "Nesingwary", value: "nesingwary-eu"},
    {label: "Nordrassil", value: "nordrassil-eu"},
    {label: "Norgannon", value: "norgannon-eu"},
    {label: "Onyxia", value: "onyxia-eu"},
    {label: "Perenolde", value: "perenolde-eu"},
    {label: "Proudmoore", value: "proudmoore-eu"},
    {label: "Quel'Thalas", value: "quel'thalas-eu"},
    {label: "Quel'dorei", value: "quel'dorei-eu"},
    {label: "Ragnaros", value: "ragnaros-eu"},
    {label: "Ravencrest", value: "ravencrest-eu"},
    {label: "Ravenholdt", value: "ravenholdt-eu"},
    {label: "Rexxar", value: "rexxar-eu"},
    {label: "Rivendare", value: "rivendare-eu"},
    {label: "Runetotem", value: "runetotem-eu"},
    {label: "Sargeras", value: "sargeras-eu"},
    {label: "Saurfang", value: "saurfang-eu"},
    {label: "Scarlet Crusade", value: "scarlet crusade-eu"},
    {label: "Scilla", value: "scilla-eu"},
    {label: "Sen'jin", value: "sen'jin-eu"},
    {label: "Sentinels", value: "sentinels-eu"},
    {label: "Shadow Council", value: "shadow council-eu"},
    {label: "Shadowmoon", value: "shadowmoon-eu"},
    {label: "Shadowsong", value: "shadowsong-eu"},
    {label: "Shandris", value: "shandris-eu"},
    {label: "Shattered Halls", value: "shattered halls-eu"},
    {label: "Shattered Hand", value: "shattered hand-eu"},
    {label: "Shu'halo", value: "shu'halo-eu"},
    {label: "Silver Hand", value: "silver hand-eu"},
    {label: "Silvermoon", value: "silvermoon-eu"},
    {label: "Sisters of Elune", value: "sisters of elune-eu"},
    {label: "Skullcrusher", value: "skullcrusher-eu"},
    {label: "Skywall", value: "skywall-eu"},
    {label: "Smolderthorn", value: "smolderthorn-eu"},
    {label: "Spinebreaker", value: "spinebreaker-eu"},
    {label: "Spirestone", value: "spirestone-eu"},
    {label: "Staghelm", value: "staghelm-eu"},
    {label: "Steamwheedle Cartel", value: "steamwheedle cartel-eu"},
    {label: "Stonemaul", value: "stonemaul-eu"},
    {label: "Stormrage", value: "stormrage-eu"},
    {label: "Stormreaver", value: "stormreaver-eu"},
    {label: "Stormscale", value: "stormscale-eu"},
    {label: "Suramar", value: "suramar-eu"},
    {label: "Tanaris", value: "tanaris-eu"},
    {label: "Terenas", value: "terenas-eu"},
    {label: "Terokkar", value: "terokkar-eu"},
    {label: "Thaurissan", value: "thaurissan-eu"},
    {label: "The Forgotten Coast", value: "the forgotten coast-eu"},
    {label: "The Scryers", value: "the scryers-eu"},
    {label: "The Underbog", value: "the underbog-eu"},
    {label: "The Venture Co", value: "the venture co-eu"},
    {label: "Thorium Brotherhood", value: "thorium brotherhood-eu"},
    {label: "Thrall", value: "thrall-eu"},
    {label: "Thunderhorn", value: "thunderhorn-eu"},
    {label: "Thunderlord", value: "thunderlord-eu"},
    {label: "Tichondrius", value: "tichondrius-eu"},
    {label: "Tol Barad", value: "tol barad-eu"},
    {label: "Tortheldrin", value: "tortheldrin-eu"},
    {label: "Trollbane", value: "trollbane-eu"},
    {label: "Turalyon", value: "turalyon-eu"},
    {label: "Twisting Nether", value: "twisting nether-eu"},
    {label: "Uldaman", value: "uldaman-eu"},
    {label: "Uldum", value: "uldum-eu"},
    {label: "Undermine", value: "undermine-eu"},
    {label: "Ursin", value: "ursin-eu"},
    {label: "Uther", value: "uther-eu"},
    {label: "Vashj", value: "vashj-eu"},
    {label: "Vek'nilash", value: "vek'nilash-eu"},
    {label: "Velen", value: "velen-eu"},
    {label: "Warsong", value: "warsong-eu"},
    {label: "Whisperwind", value: "whisperwind-eu"},
    {label: "Wildhammer", value: "wildhammer-eu"},
    {label: "Windrunner", value: "windrunner-eu"},
    {label: "Winterhoof", value: "winterhoof-eu"},
    {label: "Wyrmrest Accord", value: "wyrmrest accord-eu"},
    {label: "Ysera", value: "ysera-eu"},
    {label: "Ysondre", value: "ysondre-eu"},
    {label: "Zangarmarsh", value: "zangarmarsh-eu"},
    {label: "Zul'jin", value: "zul'jin-eu"},
    {label: "Zuluhed", value: "zuluhed-eu"}
]

export const krServers = [
    {label: "Alexstrasza", value: "alexstrasza-kr"},
    {label: "Azshara", value: "azshara-kr"},
    {label: "Burning Legion", value: "burning legion-kr"},
    {label: "Cenarius", value: "cenarius-kr"},
    {label: "Dalaran", value: "dalaran-kr"},
    {label: "Deathwing", value: "deathwing-kr"},
    {label: "Durotan", value: "durotan-kr"},
    {label: "Garona", value: "garona-kr"},
    {label: "Gul'dan", value: "gul'dan-kr"},
    {label: "Hellscream", value: "hellscream-kr"},
    {label: "Hyjal", value: "hyjal-kr"},
    {label: "Malfurion", value: "malfurion-kr"},
    {label: "Norgannon", value: "norgannon-kr"},
    {label: "Rexxar", value: "rexxar-kr"},
    {label: "Stormrage", value: "stormrage-kr"},
    {label: "Wildhammer", value: "wildhammer-kr"},
    {label: "Windrunner", value: "windrunner-kr"},
    {label: "Zul'jin", value: "zul'jin-kr"},
]

export const twServers = [
    {label: "Arthas", value: "arthas-tw"},
    {label: "Arygos", value: "arygos-tw"},
    {label: "Bleeding Hollow", value: "bleeding hollow-tw"},
    {label: "Chillwind Point", value: "chillwind point-tw"},
    {label: "Crystalpine Stinger", value: "crystalpine stinger-tw"},
    {label: "Demon Fall Canyon", value: "demon fall canyon-tw"},
    {label: "Dragonmaw", value: "dragonmaw-tw"},
    {label: "Frostmane", value: "frostmane-tw"},
    {label: "Hellscream", value: "hellscream-tw"},
    {label: "Icecrown", value: "icecrown-tw"},
    {label: "Light's Hope", value: "light's hope-tw"},
    {label: "Menethil", value: "menethil-tw"},
    {label: "Nightsong", value: "nightsong-tw"},
    {label: "Order of the Cloud Serpent", value: "order of the cloud serpent-tw"},
    {label: "Quel'dorei", value: "quel'dorei-tw"},
    {label: "Shadowmoon", value: "shadowmoon-tw"},
    {label: "Silverwing Hold", value: "silverwing hold-tw"},
    {label: "Skywall", value: "skywall-tw"},
    {label: "Spirestone", value: "spirestone-tw"},
    {label: "Stormscale", value: "stormscale-tw"},
    {label: "Sundown Marsh", value: "sundown marsh-tw"},
    {label: "Whisperwind", value: "whisperwind-tw"},
    {label: "World Tree", value: "world tree-tw"},
    {label: "Wrathbringer", value: "wrathbringer-tw"},
    {label: "Zealot Blade", value: "zealot blade-tw"}
]