export const mockShadowghastRing = {
    "Item": {
        "id": 178926,
        "description": "An exceptionally well crafted piece of jewelry worthy of being empowered by the Runecarver.",
        "name": "Shadowghast Ring",
        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_maxlvlring_red.jpg",
        "buyPrice": 100,
        "equippable": true,
        "quality": 1,
        "sellPrice": 20,
        "itemSource": {},
        "hasSockets": false,
        "isAuctionable": true,
        "upgradable": false,
        "heroicTooltip": false,
        "bonusSummary": {},
        "IsVendored": false
    },
    "Quantity": 1,
    "AHPrice": 70000000,
    "BGPrice": 70000000,
    "BGRecommendation": "Buy",
    "MissingReason": "",
    "CheapestRecipe": {
        "SpellID": 327920,
        "RecipeName": "Shadowghast Ring",
        "ComponentPrice": 91438000,
        "RecipeMakes": 1,
        "Profession": "Jewelcrafting",
        "Components": [
            {
                "Item": {
                    "id": 173170,
                    "description": "Gathered by players with the Jewelcrafting skill. Most commonly found when prospecting Phaedrum Ore.",
                    "name": "Essence of Rebirth",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_reagent_green.jpg",
                    "buyPrice": 100000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 25000,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 36915000,
                "BGPrice": 36660000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 311949,
                    "RecipeName": "Essence of Rebirth",
                    "ComponentPrice": 36660000,
                    "RecipeMakes": 1,
                    "Profession": "No Profession",
                    "Components": [
                        {
                            "Item": {
                                "id": 171831,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Phaedrum Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_phaedrite.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 15,
                            "AHPrice": 3666000,
                            "BGPrice": 3666000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 173171,
                    "description": "Gathered by players with the Jewelcrafting skill. Most commonly found when prospecting Sinvyr Ore.",
                    "name": "Essence of Torment",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_reagent_red.jpg",
                    "buyPrice": 100000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 25000,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 27400000,
                "BGPrice": 22065000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 311949,
                    "RecipeName": "Essence of Torment",
                    "ComponentPrice": 22065000,
                    "RecipeMakes": 1,
                    "Profession": "No Profession",
                    "Components": [
                        {
                            "Item": {
                                "id": 171832,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Sinvyr Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_sinvyr.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 15,
                            "AHPrice": 2206500,
                            "BGPrice": 2206500,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 178787,
                    "description": "",
                    "name": "Orboreal Shard",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_tradeskillitem_sorcererswind.jpg",
                    "buyPrice": 1250000,
                    "equippable": false,
                    "quality": 3,
                    "sellPrice": 312500,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": true
                },
                "Quantity": 10,
                "AHPrice": 12500000,
                "BGPrice": 12500000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 171428,
                    "description": "Can be bought and sold on the auction house.",
                    "name": "Shadowghast Ingot",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_blacksmithing_craftedreagent_ingot.jpg",
                    "buyPrice": 50000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 12500,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 20,
                "AHPrice": 25000000,
                "BGPrice": 20213000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 307611,
                    "RecipeName": "Shadowghast Ingot",
                    "ComponentPrice": 20213000,
                    "RecipeMakes": 2,
                    "Profession": "Blacksmithing",
                    "Components": [
                        {
                            "Item": {
                                "id": 180733,
                                "description": "Used for removing impurities from metal. Sold by Blacksmithing vendors.",
                                "name": "Luminous Flux",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_craftingreagent_flux01.jpg",
                                "buyPrice": 90000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 12500,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 4,
                            "AHPrice": 360000,
                            "BGPrice": 360000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171830,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Oxxein Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_oxxein.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 400000,
                            "BGPrice": 400000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171831,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Phaedrum Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_phaedrite.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 244400,
                            "BGPrice": 244400,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171832,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Sinvyr Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_sinvyr.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 147100,
                            "BGPrice": 147100,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171829,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Solenium Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_solenium.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 869800,
                            "BGPrice": 869800,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            }
        ],
        "ProcModifier": false,
        "CanBeMade": true
    }
}

export const mockBountiful = {
    "Item": {
        "id": 156526,
        "description": "",
        "name": "Bountiful Captain's Feast",
        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_majorfeast.jpg",
        "buyPrice": 25000,
        "equippable": false,
        "quality": 1,
        "sellPrice": 1250,
        "itemSource": {},
        "hasSockets": false,
        "isAuctionable": true,
        "upgradable": false,
        "heroicTooltip": false,
        "bonusSummary": {},
        "IsVendored": false
    },
    "Quantity": 1,
    "AHPrice": 65924700,
    "BGPrice": 10076250,
    "BGRecommendation": "Craft",
    "MissingReason": "",
    "CheapestRecipe": {
        "SpellID": 259423,
        "RecipeName": "Bountiful Captain's Feast",
        "ComponentPrice": 10076250,
        "RecipeMakes": 1,
        "Profession": "Cooking",
        "Components": [
            {
                "Item": {
                    "id": 152545,
                    "description": "",
                    "name": "Frenzied Fangtooth",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_frenziedfangtooth.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 3000000,
                "BGPrice": 3000000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154881,
                    "description": "",
                    "name": "Kul Tiramisu",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_kultiramisu.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 1250,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 3007000,
                "BGPrice": 395250,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 259413,
                    "RecipeName": "Kul Tiramisu",
                    "ComponentPrice": 395250,
                    "RecipeMakes": 10,
                    "Profession": "Cooking",
                    "Components": [
                        {
                            "Item": {
                                "id": 160711,
                                "description": "",
                                "name": "Aromatic Fish Oil",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/trade_alchemy_dpotion_e2.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 6250,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 2,
                            "AHPrice": 20000,
                            "BGPrice": 20000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": {
                                "SpellID": 273293,
                                "RecipeName": "Aromatic Fish Oil",
                                "ComponentPrice": 600000,
                                "RecipeMakes": 1,
                                "Profession": "No Profession",
                                "Components": [
                                    {
                                        "Item": {
                                            "id": 168646,
                                            "description": "",
                                            "name": "Mauve Stinger",
                                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_82_mauvestinger.jpg",
                                            "buyPrice": 2000,
                                            "equippable": false,
                                            "quality": 1,
                                            "sellPrice": 50,
                                            "itemSource": {},
                                            "hasSockets": false,
                                            "isAuctionable": true,
                                            "upgradable": false,
                                            "heroicTooltip": false,
                                            "bonusSummary": {},
                                            "IsVendored": false
                                        },
                                        "Quantity": 1,
                                        "AHPrice": 300000,
                                        "BGPrice": 300000,
                                        "BGRecommendation": "Buy",
                                        "MissingReason": "",
                                        "CheapestRecipe": null
                                    }
                                ],
                                "ProcModifier": false,
                                "CanBeMade": true
                            }
                        },
                        {
                            "Item": {
                                "id": 160400,
                                "description": "",
                                "name": "Foosaka",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_foosaka.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 625,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 5,
                            "AHPrice": 125000,
                            "BGPrice": 125000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 160705,
                                "description": "For the adventurer with a sophisticated palate.",
                                "name": "Major's Frothy Coffee",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/spell_misc_drink.jpg",
                                "buyPrice": 50,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 12,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 5,
                            "AHPrice": 250,
                            "BGPrice": 250,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 160399,
                                "description": "",
                                "name": "Wild Flour",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_wildflour.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 625,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 10,
                            "AHPrice": 250000,
                            "BGPrice": 250000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 154898,
                    "description": "",
                    "name": "Meaty Haunch",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_meatyhaunch.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 4414500,
                "BGPrice": 4414500,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 162515,
                    "description": "These fish are most prominent during the late hours of the day.",
                    "name": "Midnight Salmon",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_fish_51.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 2,
                "AHPrice": 114000,
                "BGPrice": 114000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154885,
                    "description": "",
                    "name": "Mon'Dazi",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_mondazi.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 1250,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 1260000,
                "BGPrice": 495000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 259444,
                    "RecipeName": "Mon'Dazi",
                    "ComponentPrice": 495000,
                    "RecipeMakes": 10,
                    "Profession": "Cooking",
                    "Components": [
                        {
                            "Item": {
                                "id": 160711,
                                "description": "",
                                "name": "Aromatic Fish Oil",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/trade_alchemy_dpotion_e2.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 6250,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 2,
                            "AHPrice": 20000,
                            "BGPrice": 20000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": {
                                "SpellID": 273293,
                                "RecipeName": "Aromatic Fish Oil",
                                "ComponentPrice": 600000,
                                "RecipeMakes": 1,
                                "Profession": "No Profession",
                                "Components": [
                                    {
                                        "Item": {
                                            "id": 168646,
                                            "description": "",
                                            "name": "Mauve Stinger",
                                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_82_mauvestinger.jpg",
                                            "buyPrice": 2000,
                                            "equippable": false,
                                            "quality": 1,
                                            "sellPrice": 50,
                                            "itemSource": {},
                                            "hasSockets": false,
                                            "isAuctionable": true,
                                            "upgradable": false,
                                            "heroicTooltip": false,
                                            "bonusSummary": {},
                                            "IsVendored": false
                                        },
                                        "Quantity": 1,
                                        "AHPrice": 300000,
                                        "BGPrice": 300000,
                                        "BGRecommendation": "Buy",
                                        "MissingReason": "",
                                        "CheapestRecipe": null
                                    }
                                ],
                                "ProcModifier": false,
                                "CanBeMade": true
                            }
                        },
                        {
                            "Item": {
                                "id": 160400,
                                "description": "",
                                "name": "Foosaka",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_foosaka.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 625,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 5,
                            "AHPrice": 125000,
                            "BGPrice": 125000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 160712,
                                "description": "",
                                "name": "Powdered Sugar",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_powderedsugar.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 625,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 4,
                            "AHPrice": 100000,
                            "BGPrice": 100000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 160399,
                                "description": "",
                                "name": "Wild Flour",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_wildflour.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 625,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 10,
                            "AHPrice": 250000,
                            "BGPrice": 250000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 152549,
                    "description": "",
                    "name": "Redtail Loach",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_redtailloach.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 1050000,
                "BGPrice": 1050000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154897,
                    "description": "",
                    "name": "Stringy Loins",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_stringyloins.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 607500,
                "BGPrice": 607500,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            }
        ],
        "ProcModifier": false,
        "CanBeMade": true
    }
};

export const mockMockBountiful = {
    "Item": {
        "id": 156526,
        "description": "",
        "name": "Bountiful Captain's Feast",
        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_majorfeast.jpg",
        "buyPrice": 25000,
        "equippable": false,
        "quality": 1,
        "sellPrice": 1250,
        "itemSource": {},
        "hasSockets": false,
        "isAuctionable": true,
        "upgradable": false,
        "heroicTooltip": false,
        "bonusSummary": {},
        "IsVendored": false
    },
    "Quantity": 1,
    "AHPrice": 65924700,
    "BGPrice": 10076250,
    "BGRecommendation": "Craft",
    "MissingReason": "",
    "CheapestRecipe": {
        "SpellID": 259423,
        "RecipeName": "Bountiful Captain's Feast",
        "ComponentPrice": 10076250,
        "RecipeMakes": 1,
        "Profession": "Cooking",
        "Components": [
            {
                "Item": {
                    "id": 152545,
                    "description": "",
                    "name": "Frenzied Fangtooth",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_frenziedfangtooth.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 3000000,
                "BGPrice": 3000000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154881,
                    "description": "",
                    "name": "Kul Tiramisu",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_kultiramisu.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 1250,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 3007000,
                "BGPrice": 395250,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154898,
                    "description": "",
                    "name": "Meaty Haunch",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_meatyhaunch.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 4414500,
                "BGPrice": 4414500,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 162515,
                    "description": "These fish are most prominent during the late hours of the day.",
                    "name": "Midnight Salmon",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_fish_51.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 2,
                "AHPrice": 114000,
                "BGPrice": 114000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154885,
                    "description": "",
                    "name": "Mon'Dazi",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_mondazi.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 1250,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 1260000,
                "BGPrice": 495000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 152549,
                    "description": "",
                    "name": "Redtail Loach",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_redtailloach.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 1050000,
                "BGPrice": 1050000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 154897,
                    "description": "",
                    "name": "Stringy Loins",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_stringyloins.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 625,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 15,
                "AHPrice": 607500,
                "BGPrice": 607500,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            }
        ],
        "ProcModifier": false,
        "CanBeMade": true
    }
};